### ISSUE TITLE
ERROR:root:File `u'/scripts/pyannote-structure.py'` not found.

### ISSUE THREAD

**Issue by Blair-Young** [pyannote/pyannote-video#14] opened 2016-11-07 11:46 UTC
try to run the command: 
%run /scripts/pyannote-structure.py --help with release 1.312
returns:
ERROR:root:File `u'/scripts/pyannote-structure.py'` not found in the terminal

also noticed that I'm getting an error when building the container:
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install pyannote.core[notebook]' returned a non-zero code: 2

**Comment by hbredin** [comment] 2016-11-08 17:07
Should be fixed in latest release (1.3.14).
Closing as this is likely a duplicate of #15.

**Closed as completed by hbredin** 2016-11-08 17:07 UTC
